services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: unkomorasi01
      POSTGRES_PASSWORD: unkomorasi01
      PGPASSWORD: unkomorasi01
      POSTGRES_DB: unknow
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  unknow01:
    image: unknow01
    tty: true
    volumes:
      - ../server:/srv:cached
    ports:
      - 8080:8080 # 通常実行
    depends_on:
      - postgres